### PR TITLE
fixes for the last two issues

### PR DESCRIPTION
**Pull request by newdatasystems**
the white-space stuff at the top of the file doesn't do anything and seems to screw up the regex afterwards. If you take it out you can put in a normal regex to properly treat the asterisk.

I also put in code to properly handle the [ ] quotes.

### CODE REVIEW

**Comment by newdatasystems** [comment]
by the way, I started my own project that includes these fixes, some coloration kluges and a handful of snippets (check out my profile). It's also available through the vscode extensions marketplace. Check it out.

**Comment by mattslay** [comment]
@newdatasystems  - Cool, I will check out your repo and see if the code works as promised.

**Comment by mattslay** [comment]
@newdatasystems - I see you have two repos related to this, and I can't tell which one is supposed to be your latest version? Please tell me which one is the more current?

https://github.com/newdatasystems/vscode-foxpro

or

https://github.com/newdatasystems/Visual-FoxPro-language-template-for-Visual-Studio-Code

?

**Comment by newdatasystems** [comment]
vscode-foxpro is the one that's on the marketplace. the other one is the fork of this project I made to do this pull request.

**Pull request merged**
